### PR TITLE
switch: update for latest libnx

### PR DESCRIPTION
**Pull request by Cpasjuste**

### CODE REVIEW

**Comment by fincs** [comment]
This is not the right way to fix this. The "Mutex mutex" member in SDL_cond should be removed, and SDL_CondWaitTimeout should instead use the mutex provided by the user instead of using an internal mutex. Please note that in this case it is not necessary to manually unlock/relock said mutex, as the condvar API does that inherently. I fixed the libnx condvar API precisely to match what other threading APIs expect from a condvar (including SDL's).

**Comment by Cpasjuste** [comment]
Thanks for the hint @fincs. Do you think it's ok now ?

**Comment by fincs** [comment]
Apparently SDL mutexes are [supposed to be recursive](https://wiki.libsdl.org/SDL_LockMutex). Hmm, this kind of sucks. I think you could try to pass the recursive mutex's internal non-recursive mutex to condvarWait*, instead of replacing it with a non-recursive mutex and thus breaking the SDL API.

**Review by fincs — COMMENTED** [review]
^

**Comment by Cpasjuste** [comment]
Nice catch, didn't notice the sdl recursive mutex thing :/ (or i probably did but a long time ago and forgot about it). So you would do it like this ?

**Comment by fincs** [comment]
Yes.

**Comment by Cpasjuste** [comment]
Removing the lock/unlock does make the device freeze when using sdl conds :x

**Comment by fincs** [comment]
I think I know why. I think you need to back up the other two members of the recursive mutex structure in a temporary variable, then set them to zero before calling condvarWait*. After condvarWait is done, then restore the values of those members.

**Comment by fincs** [comment]
Ping on the above? We'd like to get SDL2 fixed before we can do a libnx release.

**Comment by Cpasjuste** [comment]
Hi, i didn't found the time yet to test the changes, I will next week (so its ready for me to make the opengl implementation as soon as you release the beta mesa). I may eventually do it tomorrow.

**Comment by fincs** [comment]
Can you come on IRC for a bit?

**Pull request merged**
