### PR TITLE
switch: move to opengles 2 renderer

### PR DESCRIPTION
**Pull request by Cpasjuste**

### CODE REVIEW

**Comment by Cpasjuste** [comment]
Seems to work fine :)

**Comment by Cpasjuste** [comment]
I should add multiple resolution (videomodes) support, will do that someday.

**Comment by Cpasjuste** [comment]
We may, maybe, wait for a fix for the gpu crash problem (orange screen after a second start if hb-menu not reloaded).

**Review by fincs — COMMENTED** [review]
I've looked at the PR, and it seems to be mostly fine. I'm not very familiar with SDL, but it looks like you are reusing SDL's existing EGL/GLES2 support, which should be fine.

**Comment by carstene1ns** [comment]
:fireworks: time to recompile some things, i guess

**Pull request merged**
