### PR TITLE
switch: use c11 threads

### PR DESCRIPTION
**Pull request by Cpasjuste**

### CODE REVIEW

**Comment by rsn8887** [comment]
This definitely breaks uae4all2 sound synchronization (something with semaphores). Has this been tested with audio and sdl_mixer, etc?

**Comment by rsn8887** [comment]
@cpasjuste can you take a look? Any suggestion how I could fix it? Some include or compiler directive etc?

Sound works but is very choppy and fps goes to 60 instead of 50. It behaves as if the semaphore is completely ignored.

**Comment by Cpasjuste** [comment]
Yes, going to take a look today (if all goes well). Do you have a simple way to test it on uae? (do we need to change some config, do you have a simple game to test on).

**Comment by Cpasjuste** [comment]
I'm on it.

**Comment by Cpasjuste** [comment]
@rsn8887, seems fixed with https://github.com/devkitPro/SDL/pull/27

**Comment by rsn8887** [comment]
Yup, fixed! Thank you!!!

**Pull request merged**
