### PR TITLE
switch: support SL/SR buttons for LAYOUT_LEFT and LAYOUT_RIGHT

### PR DESCRIPTION
**Pull request by rsn8887**

### CODE REVIEW

**Comment by fincs** [comment]
Looks like we need libnx changes first. We need to redefine KEY_TOUCH to not collide with the newly found bit values, and then (and only then) afterwards, fix SDL.

EDIT: See https://github.com/switchbrew/libnx/issues/206#issuecomment-439143459

**Comment by rsn8887** [comment]
I don't understand KEY_TOUCH. What about the proposal above? Just use BIT(26), BIT(27)? No need to be specific in SDL, it just reports button numbers, nondescript.

**Comment by Cpasjuste** [comment]
What fincs means is we still should properly add/fix this in libnx. I'm not sure when I'll have the time to take a closer look, but I'll try.

**Comment by rsn8887** [comment]
Ok good to hear from you! Thanks for taking a look :)

**Comment by Cpasjuste** [comment]
From what I remember I basically do what fincs suggested at https://github.com/switchbrew/libnx/issues/206#issuecomment-439143459 in pFBA (but as SR can be left/right it have some bugs if joycons are not detached in the "good" order).

**Comment by rsn8887** [comment]
I found a way to robustly switch between split joy con and dual and handheld mode, on need for "good" order, the code is here:
https://github.com/rsn8887/uae4all2/blob/fd5f2883d92701ff9fe21e425b6ff37d6c75f453/src/gui.cpp#L198

This function is called on every frame. In it I force LAYOUT_LEFT/LAYOUT_RIGHT if split Joycon mode is on and handheld mode is off, every single frame. So as soon as the user detaches one, it is forced into LAYOUT_LEFT or LAYOUT_RIGHT mode. The OS won't allow a layout that doesn't match the controller type. If a wrong layout is set, no input is generated. LAYOUT_DEFAULT always works, but doesn't register SL/SR.

It works great, very dynamic. All button re-assignments have to be done in the code in split JoyCon mode. To ensure everything works even when Player 1 is assigned to right or left Joycon,  a check for controller TYPE_JOYCON_LEFT and TYPE_JOYCON_RIGHT is made for every controller, and re-assignments from dpad or buttons to other buttons are made depending on the type. This can be seen here:
https://github.com/rsn8887/uae4all2/blob/fd5f2883d92701ff9fe21e425b6ff37d6c75f453/src/gui.cpp#L729

The only thing I still don't understand is this: When I use four single Joycons and switch back to duals using above code, I always end up with players 1 and 3, regardless what I try. I want to go from players 1-4 (four single) to players 1 and 2 (two dual).

**Comment by Cpasjuste** [comment]
Hi @rsn8887, 
is there a reason not to use KEY_SL/KEY_SR combos keys ?

**Comment by Cpasjuste** [comment]
@rsn8887 , also, do you think we should add code similar to what you've done in uae4all to automatically handle joycons in SDL2 ?

**Comment by rsn8887** [comment]
Combo keys should be even better (less confusing) I think.

With the new changes in libnx, most of my uae4all2 code becomes unnecessary.  For example, layout_default should always be fine now, and the new joycon_holdtype function should be used to make single joycons horizontal by default. That way, button re-assignment will be automatic.

However, switching between single and dual mode still has to be done manually. I don’t know should we add an sdl function for that?

**Comment by rsn8887** [comment]
I updated uae4all2 code to work with the new libnx, and fixed single joycon->dual joycon switching.

The new code is here: 
https://github.com/rsn8887/uae4all2/blob/50f102f98730ecf89116aff544ffe0d4c8c44bb9/src/gui.cpp#L198

This is all. It has become quite simple.

`hidSetNpadJoyHoldType(HidJoyHoldType_Horizontal);` is great! No manual button re-assignments are needed anymore when using it, apart from `+` and `-`.

All other buttons apart from `+` and `-` are identical when HidJoyHoldType_Horizontal is used. 
- SL,SR register as KEY_L, KEY_R in this mode
- joystick axes are left joystick axes, even on a right joycon     
- joystick push is KEY_LSTICK, even on a right joycon
- the L,R,ZL,ZR triggers are automatically muted

The only subtlety is leaving single Joycon mode: The joycons have to be merged correctly, always merging a left with a right one. The code is here:
https://github.com/rsn8887/uae4all2/blob/50f102f98730ecf89116aff544ffe0d4c8c44bb9/src/gui.cpp#L219

**Comment by rsn8887** [comment]
I am still trying to optimize the UAE4All2 code.

I fixed the problem that there could sometimes be a "gap" in player numbers, e.g. ply 1 and ply 3, but no ply 2, when going from single to dual. 

But switching into railed (handheld) mode also requires some attention. When attaching the two "wrong" single joycons, ply1 can remain on an external single joycon. It should always be switched to the railed controllers I think, or at least to a valid pair.

I will try to fix the remaining issues in the coming days.

**Comment by Cpasjuste** [comment]
OK, thanks for the informations and "work" on that. I'll try to take a closer look too tomorrow with pfba.

**Comment by rsn8887** [comment]
Ok, here’s the final code I have settled on for uae4all2:

https://github.com/rsn8887/uae4all2/blob/a6efa3007f4b0bf6a52c978c2f35c017a22dc08f/src/gui.cpp#L197

It works pretty well. But I wouldn’t say it is perfect.  It is still possible to attach the „wrong“  controllers (e.g. ply 2 and 3) to the Switch rails and end then we end up with a „half“ player one.

**Pull request merged**
